-- -------------------------------------------------------------
-- 
-- File Name: lut-cos-8x-sfix16-quart.vho 
-- Generated by Python Script 
-- 
-- -------------------------------------------------------------
constant lut_data : vector_of_signed16(0 to 7) := (
  to_signed( 16#7EB8#,16), to_signed( 16#7C48#,16), to_signed( 16#7512#,16), to_signed( 16#695D#,16), 
  to_signed( 16#599A#,16), to_signed( 16#4666#,16), to_signed( 16#307E#,16), to_signed( 16#18B8#,16)
);
